### ISSUE TITLE
Datum zobrazovat v číselném formátu

### ISSUE THREAD

**Issue by JanBednarik** [otevrenamesta/vydej-materialu#6]
Názvy měsíců zabírají místo v tabulkách. Nahradit zobrazením v číselném formátu jako `22. 03. 2020 12:45` nebo ISO 8601 jako `2020-03-22 12:45`

**Comment by mordae** [comment]
Jsem lump a moc bych si přál, aby lidé používali ISO 8601, protože je to jediný nematoucí zápis, který je stejně jako běžné číselné zápisy big-endian.
